### ISSUE TITLE
Crash in OSX

### ISSUE THREAD

**Issue by 60-hz** [cuinjune/Ofelia#31]
I am writing some useful abstractions that makes ofelia easy to use with pd.

During this process, I found some instabilites under OSX, and no pb under Windows / Linux.

Here is an example that I tried to keep as minimal as possible, it crashed pd with two of my OSX computers 100% of the time after a few minutes and second time screen is created.

The more stack of "set:method", the quicker the crash occurs.

[Crash-OSX.pd.zip](https://github.com/cuinjune/Ofelia/files/4617895/Crash-OSX.pd.zip)

Tested with pd-0.50-2 / pd 0.50
Tested under OSX Mojave / OSX Catalina
Under windows10, it doesn't crash at all
Ofelia v3.1.0 from deken

**Comment by mrpropre** [comment]
Ok, I fixed the problem by moving  the set function from the M.bang() to M.setup() part and it works ok even in OSX now. I used set method with 3dprimitive because it was handy to change many parameters at once... but the right way might be to call every set methods separately in a function.
I don't know why only OSX has this kind of crash and not other system, maybe openGL is less permissive in OSX.
