### ISSUE TITLE
Receiving non float by multiple inlets in [ofelia]

### ISSUE THREAD

**Issue by emviveros** [cuinjune/Ofelia#51]
Hi Zack!

I know I can control outlets doing things like this:
![Captura de Tela 2021-01-28 às 03 07 46](https://user-images.githubusercontent.com/3089536/106097634-6ebd3300-6116-11eb-8de5-dc06288ef694.png)

There's a way that I can receive another pd atoms by mutiple inlets of ofelia object independently?

Maybe something like:
![Captura de Tela 2021-01-28 às 03 15 57](https://user-images.githubusercontent.com/3089536/106098072-294d3580-6117-11eb-9fd9-91c6fed3d629.png)

**Comment by cuinjune** [comment]
Hi, receiving non-float data through non-first inlets is not possible in Ofelia.
While it is possible to support other types by using "active" inlets, it will add extra overhead so I decided to use passive inlets supporting only float types. And if you want to use other types, you can always use the first inlet to receive a list of any types and handle them internally.

**Comment by emviveros** [comment]
Ok! Thank you again!! :)

**Comment by jamshark70** [comment]
I realize this is closed and nothing will be done, but... here's a use case where it would be helpful.

Pd forum user 60Hz has created some Gem-style abstractions to simplify many basic use cases, for use in workshops where it would be too much to have everyone build up Lua code from scratch.

I was working on extending these for GLSL shader support. To handle image processors, it was necessary to pass `imageID symbol` messages, to tell the next processor in the chain which module's `image` variable contains the source to operate on. That was pretty straightforward.

Next problem: shaders with two image inputs.

*If* you can pass arbitrary lists into the additional inputs, then it would be easy to have a left `imageID` message for the main image source and a right `imageID` for the auxiliary source.

Because this is not allowed, it's necessary to have for instance `imageID` and `imageID2`, both going into the left inlet, and then every image-handling abstraction needs to include (replicate) logic to output `imageID`, `imageID2`, `imageID3` as needed. Which is possible, but a lot messier.

Anyway, FWIW. I do realize that the intended design currently is to have one massive [ofelia] object that does pretty much all the drawing in one place, but... the learning curve for this is pretty nasty (the preamble just to open a window makes my head spin). Getting started really needs to be easier if it's to gain any traction in the Pd community, which is where abstractions such as 60Hz's come in.
